version: "2"
linters:
    enable:
        - govet
        - staticcheck
        - errcheck
        - unused
        - wsl
        - wsl_v5 # white space linter
        - cyclop # cyclomatic complexity
        - ineffassign # detects ineffectual assignments
        - gocritic # highly opinionated go linter
        - exhaustive # exhaustive switch cases
        - nlreturn # newline before return & branches
        - lll # long lines linter
        - importas # check for import aliases (closest to importcheck)
        - errorlint # error wrapping/fmt.Errorf checks
        - predeclared # shadowing predeclared identifiers
        - testifylint # for testify usage
        - forbidigo # forbid fmt.Print, etc
    settings:
        nlreturn:
            # Size of the block (including return statement that is still "OK"),
            # so no return split required.
            block-size: 1
        wsl_v5:
            # Allow cuddling a variable if it's used first in the immediate following block,
            # even if the statement with the block doesn't use the variable.
            # https://github.com/bombsimon/wsl/tree/main?tab=readme-ov-file#configuration
            # Default: true
            allow-first-in-block: false
            # Same as above,
            # but allows cuddling if the variable is used anywhere in the following (or nested) block.
            # https://github.com/bombsimon/wsl/tree/main?tab=readme-ov-file#configuration
            # Default: false
            allow-whole-block: true
            # If a block contains more than this number of lines,
            # the branch statement needs to be separated by whitespace.
            # https://github.com/bombsimon/wsl/tree/main?tab=readme-ov-file#configuration
            # Default: 2
            branch-max-lines: 4
            # If set to a non-negative number,
            # case blocks need to end with whitespace if exceeding this number
            # https://github.com/bombsimon/wsl/tree/main?tab=readme-ov-file#configuration
            # Default: 0
            case-max-lines: 2
            # Default checks to use.
            # Can be `all`, `none`, `default` or empty.
            # https://github.com/bombsimon/wsl/tree/main?tab=readme-ov-file#checks-and-configuration
            # Default: ""
            default: all
            # Enabled checks.
            # Will be additive to any presets.
            # https://github.com/bombsimon/wsl/tree/main?tab=readme-ov-file#checks-and-configuration
            # Default: []
            enable:
                - assign
                - branch
                - decl
                - defer
                - expr
                - for
                - go
                - if
                - inc-dec
                - label
                - range
                - return
                - select
                - send
                - switch
                - type-switch
                - append
                - assign-exclusive
                - assign-expr
                - err
                - leading-whitespace
                - trailing-whitespace
            # Disable checks.
            # Will be subtractive to any preset.
            # https://github.com/bombsimon/wsl/tree/main?tab=readme-ov-file#checks-and-configuration
            # Default: []
            disable: []
run:
    timeout: 5m
