format = """
[┌─](color_debian_red)\
$os\
$username\
$directory\
$nodejs\
$python\
$docker_context\
$fill\
$git_branch\
$time\
$line_break\
[└─▪](fg:color_debian_red)$character
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
color_debian_red = '#AF0032'

[fill]
disabled = false
symbol = "─"
style = "fg:color_debian_red"

[username]
disabled = false

[character]
disabled = false

[os]
disabled = false
style = "fg:color_debian_red"
format = '[ $symbol]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[directory]
truncation_length = 1
truncation_symbol = "…/"

[git_branch]
style = "bg:color_aqua"
# format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'
format = '[[ $symbol $branch ](fg:color_fg0)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )]'

[nodejs]
symbol = ""
format = '[[ $symbol( $version) ]]'

[c]
symbol = " "
format = '[[ $symbol( $version) ]]'

[rust]
symbol = ""
format = '[[ $symbol( $version) ]]'

[golang]
symbol = ""
format = '[[ $symbol( $version) ]]'

[php]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
# style = "bg:color_blue"
# format = '[[ $symbol( $version $virtualenv) ](fg:color_fg0 bg:color_blue)]($style)'
# format = '[[ $symbol( $virtualenv) ](fg:color_fg0 bg:color_blue)]($style)'
format = '[[ $symbol]( $virtualenv) ]($style)'

[docker_context]
symbol = ""
# style = "bg:color_bg3"
# format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
format = '[[ $symbol( $context) ]]'

[time]
disabled = false
time_format = "%R"
format = '[[ <$time> ](fg:color_debian_red)]($style)'
# format = '[[ $time ]]($style)'

[line_break]
disabled = false

